#!/bin/sh

#==============================================================================
# ti
# File ID: db9d9ec0-fa70-11dd-9fc7-000475e441b9
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=ti
VERSION=0.2.0

opt_dry_run=0
opt_edit=0
opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-n|--dry-run) opt_dry_run=1; shift ;;
	-e|--edit) opt_edit=1; shift ;;
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	-) break ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))
tag=ti

test "$opt_dry_run" = "1" && sim=echo || sim=

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Display various status messages about the current tty with sess 
information and optionally enter a comment into the suuid history with 
the tag "$tag". Used for various off-hand comments and notes.

Usage: $progname [options] [comment]

Options:

  -e, --edit
    Edit the comment with the default text editor used by suuid(1).
  -h, --help
    Show this help.
  -n, --dry-run
    Don't log the comment, only send the suuid command that would be 
    executed to stdout.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

if test "$opt_edit" = "1"; then
	cmt="--"
else
	cmt="$*"
fi

test -z "$cmt" || $sim suuid -t $tag -c "$cmt" || {
	echo $progname: suuid error >&2
	exit 1
}
LC_ALL=C stty -a | grep speed
echo -n "$(date +"%Y-%m-%d %H:%M:%S %z") "
tty
test -z "$SESS_UUID" || \
	printf 'SESS_UUID = \n%s\n' \
	       "$(echo $SESS_UUID | tjah | sed 's/,/\n    ,/g' | sortuuid)"
test -z "$LOGGING_UUID" || {
	echo LOGGING_UUID = $LOGGING_UUID
	cd $HOME/log/script || {
		echo $progname: $HOME/log/script: Cannot chdir >&2
		exit 1
	}
	ls | grep $LOGGING_UUID | grep scrlog
}

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
