#!/bin/sh

# ti
# File ID: db9d9ec0-fa70-11dd-9fc7-000475e441b9
# Terminal Identification – for å identifisere skjermhøyde etc ved 
# logging.

progname=ti
VERSION=0.0.0

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Options:

  -h, --help
    Show this help.
  --version
    Show version information.

END
    exit 0
fi
if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

[ -z "$*" ] || suuid -t ti -c "$*" || { echo ti: suuid error >&2; exit 1; }
LC_ALL=C stty -a | grep speed
echo -n "`date -Iseconds` "
tty
[ -z "$SESS_UUID" ] || printf 'SESS_UUID = \n%s\n' "$(echo $SESS_UUID | tjah | sed 's/,/\n    ,/g' | sortuuid)"
[ -z "$LOGGING_UUID" ] || {
    echo LOGGING_UUID = $LOGGING_UUID
    cd $HOME/log/script || { echo ti: $HOME/log/script: Cannot chdir >&2; exit 1; }
    ls | grep $LOGGING_UUID | grep scrlog
}
