#!/bin/bash

#=======================================================================
# tjah
# File ID: 79f9fe38-44d2-11e2-a6e3-0016d364066c
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=tjah
VERSION=0.0.0

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Options:

  -h, --help
    Show this help.
  --version
    Show version information.

END
    exit 0
fi
if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

echo -n ,$(
tr '\t ,' '\n' |
finduuid -lu |
sortuuid |
tr '\n' ,
)
