# Makefile
# File ID: 6454cafe-4b04-11e6-8c85-02010e0a6634

CC = cc
LD = cc
CCFLAGS = -Wall -Wextra -Werror -O0 -c -g
LDFLAGS = -Wall -Wextra -Werror
LIBS =

OBJS =
CFILES =
HFILES =
DEPS = $(HFILES) Makefile

.PHONY: all
all:

.PHONY: clean
clean:

.PHONY: edit
edit:
	$(EDITOR) $$(git ls-files)

.PHONY: test
test:
