#!/bin/sh

#==============================================================================
# fake-editor
# File ID: 16f2835e-c78c-11e7-835b-f74d993421b0
#
# Simulate external editor.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=fake-editor
VERSION=0.1.0

outfile="$1"

echo Text from editor >$outfile

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
