/*
 * strings.c
 * File ID: bfaee004-3a99-11e6-a49d-e9fd2f75d24e
 *
 * (C)opyleft 2016- Øyvind A. Holm <sunny@sunbase.org>
 *
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "suuid.h"

/*
 * mystrdup() - Custom implementation of `strdup()`, which isn't available in 
 * C99. Returns a pointer to an allocated duplicate of `s`. If `malloc()` fails 
 * or `s` is NULL, it returns NULL.
 */

char *mystrdup(const char *s)
{
	size_t size;
	char *p;

	if (!s)
		return NULL;
	size = strlen(s);
	p = malloc(size + 1);
	if (!p)
		return NULL; /* gncov */
	memcpy(p, s, size);
	p[size] = '\0';

	return p;
}

/*
 * allocstr_va() - Returns pointer to allocated string generated by providing 
 * printf()-like format and va_list. Returns NULL on error.
 */

char *allocstr_va(const char *format, va_list ap)
{
	char *p;
	int needed;
	va_list ap_copy;
	size_t size;

	assert(format);
	if (!format)
		return NULL; /* gncov */

	va_copy(ap_copy, ap);
	needed = vsnprintf(NULL, 0, format, ap_copy);
	va_end(ap_copy);

	if (needed < 0)
		return NULL; /* gncov */

	size = (size_t)needed + 1;
	p = malloc(size);
	if (!p)
		return NULL; /* gncov */

	needed = vsnprintf(p, size, format, ap);
	if (needed < 0) {
		free(p); /* gncov */
		return NULL; /* gncov */
	}

	return p;
}

/*
 * allocstr() - Returns pointer to allocated string generated by providing 
 * printf()-like arguments. Returns NULL on error.
 */

char *allocstr(const char *format, ...)
{
	va_list ap;
	char *retval;

	assert(format);
	if (!format)
		return NULL; /* gncov */

	va_start(ap, format);
	retval = allocstr_va(format, ap);
	va_end(ap);

	return retval;
}

/*
 * count_substr() - Returns the number of non-overlapping occurrences of 
 * substring `substr` in string `s`.
 */

size_t count_substr(const char *s, const char *substr)
{
	size_t count = 0, len_ss;
	const char *p = s;

	if (!s || !substr || !*s || !*substr)
		return 0;

	len_ss = strlen(substr);
	while ((p = strstr(p, substr)) != NULL) {
		count++;
		p += len_ss;
	}

	return count;
}

/*
 * str_replace() - Returns an allocated string where all substrings `s1` are 
 * replaced with the string `s2` in string `s`.
 *
 * Returns NULL if any errors occur or if `s`, `s1` or `s2` are NULL.
 *
 * If `s1` is empty, an allocated copy of `s` is returned.
 */

char *str_replace(const char *s, const char *s1, const char *s2)
{
	size_t len_s1, len_s2, count, new_len;
	const char *tmp, *src;
	char *buf, *dest;

	if (!s || !s1 || !s2)
		return NULL;

	len_s1 = strlen(s1);
	len_s2 = strlen(s2);
	count = count_substr(s, s1);

	if (!*s || !*s1 || !count)
		return allocstr("%s", s);

	new_len = strlen(s) + count * (len_s2 - len_s1);
	buf = malloc(new_len + 1);
	if (!buf)
		return NULL; /* gncov */

	dest = buf;
	src = s;
	while ((tmp = strstr(src, s1)) != NULL) {
		size_t len_before = (size_t)(tmp - src);

		memcpy(dest, src, len_before);
		dest += len_before;

		memcpy(dest, s2, len_s2);
		dest += len_s2;

		src = tmp + len_s1;
	}
	strcpy(dest, src);

	return buf;
}

#if defined(UNUSED)
/*
 * squeeze_chars() - Modify s directly by replacing all repeated characters in 
 * chars with a single char. Returns s if ok, NULL if error.
 */

char *squeeze_chars(char *s, const char *chars)
{
	char *p = s, *p2, *buf;

	assert(chars);
	assert(*chars);

	if (!s || !*s)
		return s;

	buf = mystrdup(s);
	if (!buf) {
		failed("mystrdup()");
		return NULL;
	}
	memset(buf, 0, strlen(s));

	p2 = buf;
	while (*p) {
		if (!strchr(chars, *p) || p2 == buf || *p != *(p2 - 1))
			*p2++ = *p;
		p++;
	}

	memcpy(s, buf, strlen(buf) + 1);
	free(buf);

	return s;
}
#endif

/*
 * string_to_lower() - Convert all characters in str to lower case.
 * Returns str.
 */

char *string_to_lower(char *str)
{
	char *p = str;

	if (!p)
		return p;

	while (*p) {
		*p = (char)tolower((unsigned char)*p);
		p++;
	}

	return str;
}

/*
 * trim_str_front() - Modify dest by removing initial whitespace. Returns dest.
 */

char *trim_str_front(char *dest)
{
	char *p = dest;
	size_t size;

	assert(dest);

	size = strlen(dest);
	while (p < dest + size && isspace((unsigned char)*p))
		p++;
	if (p == dest)
		return dest; /* Nothing needs to be done */
	memmove(dest, p, strlen(p) + 1);

	return dest;
}

/*
 * trim_str_end() - Modify dest by removing whitespace from the end of the 
 * string. Returns dest.
 */

char *trim_str_end(char *dest)
{
	char *p;
	size_t size;

	assert(dest);

	size = strlen(dest);
	if (!size)
		return dest;
	p = dest + size - 1;
	while (p > dest && isspace((unsigned char)*p))
		*p-- = '\0';

	return dest;
}

/*
 * The utf8_check() function scans the '\0'-terminated string starting at s. It 
 * returns a pointer to the first byte of the first malformed or overlong UTF-8 
 * sequence found, or NULL if the string contains only correct UTF-8. It also 
 * spots UTF-8 sequences that could cause trouble if converted to UTF-16, 
 * namely surrogate characters (U+D800..U+DFFF) and non-Unicode positions 
 * (U+FFFE..U+FFFF). This routine is very likely to find a malformed sequence 
 * if the input uses any other encoding than UTF-8. It therefore can be used as 
 * a very effective heuristic for distinguishing between UTF-8 and other 
 * encodings.
 *
 * I wrote this code mainly as a specification of functionality; there are no 
 * doubt performance optimizations possible for certain CPUs.
 *
 * Markus Kuhn <http://www.cl.cam.ac.uk/~mgk25/> -- 2005-03-30
 * License: http://www.cl.cam.ac.uk/~mgk25/short-license.html
 *
 * Modifications by Øyvind A. Holm <sunny@sunbase.org>:
 *
 *   2016-06-29 - Receive and return regular char * instead of unsigned char * 
 *                to avoid casting everywhere.
 *   2016-07-04 - Add assert() to check that the text argument is not NULL.
 *   2016-07-09 - Add const modifier to text argument.
 */

const char *utf8_check(const char *text)
{
	const unsigned char *s = (const unsigned char *)text;

	assert(text);

	while (*s) {
		if (*s < 0x80) {
			/* 0xxxxxxx */
			s++;
		} else if ((s[0] & 0xe0) == 0xc0) {
			/* 110XXXXx 10xxxxxx */
			if ((s[1] & 0xc0) != 0x80
			    || (s[0] & 0xfe) == 0xc0) /* overlong? */
				return (const char *)s;
			else
				s += 2;
		} else if ((s[0] & 0xf0) == 0xe0) {
			/* 1110XXXX 10Xxxxxx 10xxxxxx */
			if ((s[1] & 0xc0) != 0x80
			    || (s[2] & 0xc0) != 0x80
			    || (s[0] == 0xe0
			        && (s[1] & 0xe0) == 0x80) /* overlong? */
			    || (s[0] == 0xed
			        && (s[1] & 0xe0) == 0xa0) /* surrogate? */
			    || (s[0] == 0xef && s[1] == 0xbf
			        && (s[2] & 0xfe) == 0xbe)) /* U+FFFE/U+FFFF? */
				return (const char *)s;
			else
				s += 3;
		} else if ((s[0] & 0xf8) == 0xf0) {
			/* 11110XXX 10XXxxxx 10xxxxxx 10xxxxxx */
			if ((s[1] & 0xc0) != 0x80
			    || (s[2] & 0xc0) != 0x80
			    || (s[3] & 0xc0) != 0x80
			    || (s[0] == 0xf0
			        && (s[1] & 0xf0) == 0x80) /* overlong? */
			    || (s[0] == 0xf4 && s[1] > 0x8f)
			    || s[0] > 0xf4) /* > U+10FFFF? */
				return (const char *)s;
			else
				s += 4;
		} else {
			return (const char *)s;
		}
	}

	return NULL;
}

/* vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 : */
